name: slotboard_copperframe
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/flarebyte/slotboard_copperframe

environment:
  sdk: ^3.4.4
  flutter: ">=3.0.0"

dependencies:
   flutter:
      sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

