name: slotboard_copperframe
description: Slot it sort it sit back and relax
version: 0.3.0
repository: https://github.com/flarebyte/slotboard_copperframe

environment:
  sdk: ^3.4.4
  flutter: "3.24.0"

dependencies:
   flutter:
      sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

